spring:
    datasource:
        driver-class-name=com.mysql.jdbc.Driver
        url: jdbc:mysql://database:3306/jevent_event_dev?createDatabaseIfNotExist=true
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update