spring:
  cloud:
    consul:
      host: 172.23.16.1
      port: 8500
      discovery:
        instance-id: "${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,99999]}"
        health-check-url: http://localhost:8081/actuator/health
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
server:
  port: 8081
