spring:
  cloud:
    consul:
      port: 8500
      discovery:
        instance-id: "${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,99999]}"
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
server:
  port: 0
  
