spring:
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: "${spring.application.name}:${random.int[1,99999]}"
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
server:
  port: 8081