spring:
  datasource:
    password: mysqlpass
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jevents_event_dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20