spring:
  cloud:
    consul:
      host: discovery
      discovery:
        instanceId: ${spring.application.name}:${server.port}:${random.value}
        health-check-url: http://ticket-service:8082/actuator/health
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
management:
  endpoints:
    web:
      exposure:
        include: refresh,health